[/]
calculator=['Calculator']
control-center=['<Super>s']
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
email=@as []
help=@as []
terminal=@as []

[custom-keybindings/custom0]
binding='Print'
command='flatpak run  org.flameshot.Flameshot gui'
name='flameshort'

[custom-keybindings/custom1]
binding='<Super>t'
command='gnome-terminal --working-directory="$PWD"'
name='Open termial in current dir'
