[/]
begin-move=['<Super>m']
begin-resize=['<Super>r']
close=['<Super>q']
minimize=@as []
switch-applications=['<Alt>Tab']
switch-applications-backward=['<Shift><Alt>Tab']
switch-group=['<Alt>grave']
switch-group-backward=['<Shift><Alt>grave']
switch-windows=@as []
switch-windows-backward=@as []
toggle-maximized=['<Super>Up']
unmaximize=@as []
